### ISSUE TITLE
React 16.8.1 causing useContext error log

### ISSUE THREAD

**Issue by AndiF** [dai-shi/react-hooks-global-state#5]
With React 16.8.1 I noticed the following error log:
`Warning: useContext() second argument is reserved for future use in React. Passing it is not supported.`

I am not sure about the intention of the 2nd parameter here:
const state = useContext(context, 1 << index);
but I guess it can simply be removed ?

**Comment by malerba118** [comment]
Also encountering this

**Comment by dai-shi** [comment]
This is called `observedBits` which is undocumented and unstable.

Let's say we have a state like: `{ counter1: 0, counter2: 0 }` and we `useGlobalState('counter1')` in a component "A". We want to avoid rendering A when only counter2 is updated, and that's how `observedBits` is currently used. It is supposed to be super efficient.

Now, since React 16.8 clearly warns the use of this, I'm wondering what I should do with it...

**Comment by dai-shi** [comment]
https://github.com/facebook/react/pull/14729#issuecomment-461279892
This is exactly the same here. Cc @gaearon @benwiley4000

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/14815#issuecomment-462194923

**Comment by dai-shi** [comment]
Ben and Dan, thanks so much! I will look into it.

**Comment by dai-shi** [comment]
Published v0.7.0.
